export const ActionTypes = {
    SET_ROOMS: "SET_ROOMS",
    SELECTED_ROOMS: "SELECTED_ROOMS",
    REMOVE_SELECTED_ROOMS: "REMOVE_SELECTED_ROOMS",
    FILTER_ROOMS_BY_PRICE:"REMOVE_SELECTED_ROOMS",
    SET_FLOORS:"SET_FLOORS",
    SELECTED_FLOORS:"SELECTED_FLOORS",
    SET_BRON:"SET_BRON",
  };